id = "laravel"
name = "Laravel"
version = "0.2.1"
schema_version = 1
authors = ["croustibat <https://github.com/croustibat>"]
description = "Complete Laravel support: Blade templates, PHP, Pint formatting, Artisan commands, snippets, and more"
repository = "https://github.com/croustibat/zed-laravel"

[grammars.blade]
repository = "https://github.com/EmranMR/tree-sitter-blade"
commit = "cc764dadcbbceb3f259396fef66f970c72e94f96"

[grammars.php_only]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "b2278dbac9d58b02653fe6a8530ccebc492e4ed4"
path = "php_only"

[language_servers.laravel-ls]
name = "Laravel Language Server"
language = "Blade"

[language_servers.intelephense]
name = "Intelephense"
language = "Blade"
language_ids = { Blade = "blade" }
