id = "laravel"
name = "Laravel"
version = "0.2.0"
schema_version = 1
authors = ["croustibat <https://github.com/croustibat>"]
description = "Complete Laravel support: Blade templates, PHP, Pint formatting, Artisan commands, snippets, and more"
repository = "https://github.com/croustibat/zed-laravel"

[grammars.blade]
repository = "https://github.com/EmranMR/tree-sitter-blade"
rev = "v0.14.0"

[grammars.php]
repository = "https://github.com/tree-sitter/tree-sitter-php"
rev = "v0.23.9"

[language_servers.laravel-ls]
name = "Laravel Language Server"
language = "Blade"

[language_servers.intelephense]
name = "Intelephense"
language = "PHP"
