name = "PHP"
grammar = "php"
path_suffixes = ["php"]
line_comments = ["// ", "# "]
block_comment = ["/* ", " */"]
autoclose_before = ";:.,=}])"
word_characters = ["_", "$"]

[brackets]
"(" = ")"
"[" = "]"
"{" = "}"
"<" = ">"

[language_servers]
servers = ["intelephense"]

[formatter]
external = {
    command = "sh"
    arguments = [
        "-c",
        "if [ -f vendor/bin/pint ]; then cat > {buffer_path} && ./vendor/bin/pint --quiet {buffer_path} 2>/dev/null && cat {buffer_path}; elif command -v ./vendor/bin/sail >/dev/null 2>&1 && ./vendor/bin/sail ps | grep -q 'laravel.test'; then ./vendor/bin/sail php ./vendor/bin/pint --quiet {buffer_path} 2>/dev/null && cat {buffer_path}; else cat; fi"
    ]
}
